<?php
/**
 * Created by PhpStorm.
 * User: robattfield
 * Date: 19-Mar-2015
 * Time: 00:04
 */

use RattfieldNz\UrlValidation\Helpers;


class HelpersTest extends PHPUnit_Framework_TestCase {

    public function testArrayToStringOnNullArray()
    {
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
